status:
    path: /
    controller: App\Presentation\Web\Controller\ApplicationController::statusAction

specification:
    path: /specification
    controller: App\Presentation\Web\Controller\ApplicationController::specificationAction

show:
    path: /votes
    controller: App\Presentation\Web\Controller\VoteController::showAction
    methods: [GET]

create:
    path: /votes
    controller: App\Presentation\Web\Controller\VoteController::createAction
    methods: [POST]