status:
    path: /
    controller: App\Presentation\Web\Controller\ApplicationController::statusAction

specification:
    path: /specification
    controller: App\Presentation\Web\Controller\ApplicationController::specificationAction

rating:
    path: /rating
    controller: App\Presentation\Web\Controller\ApplicationController::ratingAction
    methods: [GET]

vote:
    path: /vote
    controller: App\Presentation\Web\Controller\ApplicationController::voteAction
    methods: [POST]