parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Presentation\Web\Controller\:
        resource: '../src/Presentation/Web/Controller'
        tags: ['controller.service_arguments']

    PDO:
        class: PDO
        arguments:
            $dsn: '%env(DATABASE_DNS)%'
            $username: '%env(DATABASE_USERNAME)%'
            $passwd: '%env(DATABASE_PASSWORD)%'

    App\Infrastructure\Persistence\PDO\VoteRepository: ~
    App\Domain\VoteRepositoryInterface: '@App\Infrastructure\Persistence\PDO\VoteRepository'

    MongoDB\Database:
        factory: ['App\Infrastructure\Persistence\MongoDB\DatabaseFactory', 'build']
        arguments: ['%env(MONGODB_DNS)%']

    App\Domain\RatingRepositoryInterface: '@App\Infrastructure\Persistence\MongoDB\RatingRepository'

    Redis:
        class: Redis
        autowire: false
        factory: ['App\Infrastructure\Queue\RedisFactory', 'build']
        arguments: ['%env(REDIS_DSN)%']

    App\Infrastructure\ServiceBus\SymfonyQueryBus:
        arguments:
            $mapping:
                'App\Application\Query\RatingQuery': '@App\Application\Query\RatingQueryHandler'

    App\Application\QueryBusInterface: '@App\Infrastructure\ServiceBus\SymfonyQueryBus'

    App\Infrastructure\ServiceBus\SymfonyCommandBus:
        arguments:
            $mapping:
                'App\Application\Command\CreateVoteCommand': '@App\Application\Command\CreateVoteCommandHandler'
                'App\Application\Command\UpdateRatingCommand': '@App\Application\Command\UpdateRatingCommandHandler'

    App\Application\CommandBusInterface: '@App\Infrastructure\ServiceBus\SymfonyCommandBus'

    # Logger
    App\Infrastructure\Logger\MonologLogger:
        arguments:
            $name: 'APPLICATION'
            $path: '%kernel.project_dir%/%env(LOG_DIRECTORY)%/%kernel.environment%.log'
    App\Application\LoggerInterface: '@App\Infrastructure\Logger\MonologLogger'