parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Presentation\Web\Controller\:
        resource: '../src/Presentation/Web/Controller'
        tags: ['controller.service_arguments']

    PDO:
        class: PDO
        arguments:
            $dsn: '%env(DATABASE_DNS)%'
            $username: '%env(DATABASE_USERNAME)%'
            $passwd: '%env(DATABASE_PASSWORD)%'

    App\Infrastructure\Persistence\PDOVoteRepository: ~
    App\Domain\VoteRepositoryInterface: '@App\Infrastructure\Persistence\PDOVoteRepository'

    App\Infrastructure\ServiceBus\SymfonyQueryBus:
        arguments:
            $mapping:
                'App\Application\Query\RatingQuery': ['@App\Application\Query\RatingQueryHandler']

    App\Application\QueryBusInterface: '@App\Infrastructure\ServiceBus\SymfonyQueryBus'

    App\Application\Command\CreateVoteCommandHandler: ~

    App\Application\ServiceBus\CommandBus:
        calls:
        - [register, ['@App\Application\Command\CreateVoteCommandHandler']]
