name: Continous integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: bcmath
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install --prefer-dist
